/**
 * PreToolUse on Edit and Write: the files nobody hand-edits, with the reason
 * each time so the model does the right thing instead.
 *
 * A key ending in `/` covers everything under it, except the hand-written
 * files in `EDITABLE`. Answers with the JSON deny
 * shape rather than exit 2 so the reason reaches the model verbatim and the
 * turn continues.
 */
import { readInput, repoRelative, repoRoot } from "./lib.mjs";

const PROTECTED = new Map([
  ["CLAUDE.md", "a symlink to AGENTS.md; edit AGENTS.md"],
  [
    "src-tauri/gen/",
    "written by the Tauri CLI from the capability files and plugins; change src-tauri/capabilities/ and build",
  ],
  [
    "public/wasm/",
    "built in the LibRaw, Radiance and hdrgen forks and copied in; versions.json is regenerated by `npm run wasm:versions` from those checkouts",
  ],
  [".env.local", "personal, untracked config; tell the user what to set"],
]);

/** Hand-written files inside a protected directory. */
const EDITABLE = new Set(["public/wasm/README.md"]);

const input = readInput();
const cwd = input.cwd ?? process.cwd();
const path = repoRelative(repoRoot(cwd), input.tool_input?.file_path ?? "");
const match = EDITABLE.has(path)
  ? undefined
  : [...PROTECTED.keys()].find((key) =>
      key.endsWith("/") ? path.startsWith(key) : path === key
    );

if (match) {
  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: `${path} is ${PROTECTED.get(match)}.`,
      },
    })
  );
}
